### ISSUE TITLE
Using own Icons

### ISSUE THREAD

**Issue by miku86** [ankane/mapkick.js#1]
Hello Andrew,

thanks for your great effort,
mapkick runs really smoothly.

I tried to use my own icons by editing my js file:
`new Mapkick.Map('map', data, {
        icon: '<my-icon>'
      });
`
but that didn't work.

So I edited [mapkick.js](https://github.com/ankane/mapkick.js/blob/master/mapkick.js#L214)
`"icon-image": "<my-icon>",` 
in multiple ways,
but only Maki Icons are working.

So I thoroughly browsed through [mapbox-gl.js](https://api.tiles.mapbox.com/mapbox-gl-js/v0.43.0/mapbox-gl.js)
to find 26 places where `icon-image` is used in (for me) cryptic ways.

I would love to hear some hint or advice how to solve this issue.

Thanks and have a nice day
Michael

**Comment by ankane** [comment]
Hey @miku86, custom icons aren't supported yet, but can probably be added pretty easily if you want to contribute. Here's how the default marker is loaded: https://github.com/ankane/mapkick.js/blob/fa0602797a346fa612f36f27d6e77a3e186505db/mapkick.js#L312

**Comment by ankane** [comment]
Cleaning up issues. For future readers, still happy to review a PR.
