### ISSUE TITLE
Make it a Web Component

### ISSUE THREAD

**Issue by Danny-Engelman** [ankane/mapkick.js#5]
If this counts as 1 line of javascript 

Then when you wrap it in a modern native javascript Web Component  ``<map-kick>`` it would count as ZERO lines of JavaScript

**Comment by ankane** [comment]
Hey @Danny-Engelman, thanks for the suggestion, and sorry for the delay. It's an interesting idea, but don't want to support an additional interface right now (however, if someone creates this, feel free to share).
