### ISSUE TITLE
Mapkick with Nextjs

### ISSUE THREAD

**Issue by Sebasssssss** [ankane/mapkick.js#7]
Hello! I've been trying to use mapkick with my Nextjs project (I'm using app dir, just in case if it's relevant) and I can't get it to work. Is there any example of how should I do it in order to get it working?

**Comment by ankane** [comment]
Hi @Sebasssssss, unfortunately, I don't have the bandwidth to help with this, but the installation instructions should work with any framework that can serve static files.
